import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Women Bandhani Cotton Rayon Anarkali Kurta  (Maroon)",
    img: "https://rukminim1.flixcart.com/image/872/1046/l572ufk0/kurta/c/z/n/xl-gw1016-gudwears-original-imagfxaqekkxtrvm.jpeg?q=50",
    price: 1999,
    category: "Women",
    inStock: true,
    fastDelivery: true,
    rating: 4,
    originalPrice: 4000,
  },

  {
    _id: uuid(),
    title: "Women Solid Viscose Rayon Straight Kurta  (Dark Blue)",
    img: "https://rukminim1.flixcart.com/image/880/1056/kst9gnk0/kurta/z/r/g/xxl-rf-184-petrol-blue-new4u-original-imag6as2xts2q2b5.jpeg?q=50",
    price: 2999,
    category: "Women",
    inStock: true,
    fastDelivery: true,
    rating: 5,
    originalPrice: 5000,
  },
  {
    _id: uuid(),
    title: "Casual Regular Sleeves Solid Women White Top",
    img: "https://rukminim1.flixcart.com/image/872/1046/j1l10nk0/top/z/s/w/s-1764443-roadster-original-imaeswzb7hzkymxg.jpeg?q=50",
    price: 3999,
    category: "Women",
    inStock: true,
    fastDelivery: true,
    rating: 4,
    originalPrice: 5000,
  },
  {
    _id: uuid(),
    title: "Women Printed Viscose Rayon Flared Kurta  (Black) ",
    img: "https://rukminim1.flixcart.com/image/880/1056/xif0q/kurta/y/p/e/l-4colour-flower-kurti-anushansa-original-imagc94fvhuzwfag-bb.jpeg?q=50",
    price: 2499,
    category: "Women",
    inStock: true,
    fastDelivery: true,
    rating: 4,
    originalPrice: 4000,
  },
  {
    _id: uuid(),
    title: "Striped Men Round Neck Pink T-Shirt",
    img: "https://rukminim1.flixcart.com/image/872/1046/kk8mcnk0/t-shirt/o/8/d/xxl-rc24solidguava-roden-original-imafzmskgmukzh6h.jpeg?q=50",
    price: 1999,
    category: "Men",
    inStock: true,
    fastDelivery: true,
    rating: 4,
    originalPrice: 3000,
  },
  {
    _id: uuid(),
    title: "Kids-wear Baby Boy Girl Clothes T-shirt Pant Set 100% Cotton Blue",
    img: "https://res.cloudinary.com/dffedqurw/image/upload/v1649316236/samples/61EW3tDSMaL._AC_UL480_FMwebp_QL65__gi6tmk.webp",
    price: 1099,
    category: "Kids",
    inStock: true,
    fastDelivery: true,
    rating: 3,
    originalPrice: 2200,
  },

  {
    _id: uuid(),
    title:
      "Women's Grey Cotton Abstract Printed Unstitched Salwar Suit Material",
    img: "https://m.media-amazon.com/images/I/91QLglbhFjL._UX569_.jpg",
    price: 3999,
    category: "Women",
    inStock: true,
    fastDelivery: true,
    rating: 4,
    originalPrice: 4599,
  },
  {
    _id: uuid(),
    title: "Bon Organik Rang Barse Holi Tshirt For Boys",
    img: "https://m.media-amazon.com/images/I/81-XVctkfDL._UX679_.jpg",
    price: 2199,
    category: "Kids",
    inStock: true,
    fastDelivery: true,
    rating: 4,
    originalPrice: 3200,
  },

  {
    _id: uuid(),
    title: "Women's Crepe Printed Unstitiched Dress Material",
    img: "https://m.media-amazon.com/images/I/719i3bxckTL._UY741_.jpg",
    price: 2999,
    category: "Women",
    inStock: true,
    fastDelivery: true,
    rating: 2,
    originalPrice: 4999,
  },

  {
    _id: uuid(),
    title: "Baby Boy's & Baby Girl's Jumbo The Elephant Dungaree ",
    img: "https://m.media-amazon.com/images/I/61cVfAWys7L._UX679_.jpg",
    price: 1149,
    category: "Kids",
    inStock: true,
    fastDelivery: true,
    rating: 2,
    originalPrice: 1900,
  },

  {
    _id: uuid(),
    title: "YC YOUNGCASH Full Sleeve Solid Men ",
    img: "https://rukminim1.flixcart.com/image/872/1046/krf91u80/sweatshirt/l/g/u/m-yc35-yc-youngcash-original-imag57r9czgyhhgg.jpeg?q=50",
    price: 1399,
    category: "Men",
    inStock: true,
    fastDelivery: true,
    rating: 3,
    originalPrice: 1800,
  },

  {
    _id: uuid(),
    title: "Solid Men Henley Neck Dark Blue T-Shirt",
    img: "https://rukminim1.flixcart.com/image/872/1046/kf5pzm80-0/t-shirt/o/i/o/l-bnvhenful-z14-blive-original-imafvzpkbmquycxq.jpeg?q=50",
    price: 1299,
    category: "Men",
    inStock: true,
    fastDelivery: true,
    rating: 3.6,
    originalPrice: 1990,
  },

  {
    _id: uuid(),
    title: "Men's Slim Fit Full Sleeves Printed Casual Shirt",
    img: "https://m.media-amazon.com/images/I/615ElM9ls6L._AC_UL480_FMwebp_QL65_.jpg",
    price: 1999,
    category: "Men",
    inStock: true,
    fastDelivery: true,
    rating: 3,
    originalPrice: 3000,
  },
  {
    _id: uuid(),
    title: "Men Regular Fit Checkered Spread Collar Casual Shirt",
    img: "https://rukminim1.flixcart.com/image/872/1046/l0jwbrk0/shirt/i/l/o/m-praw21csh039a-provogue-original-imagcbcftqphjnhe.jpeg?q=50",
    price: 2199,
    category: "Men",
    inStock: true,
    fastDelivery: true,
    rating: 4.5,
    originalPrice: 4000,
  },
  {
    _id: uuid(),
    title: "Men's Slim Fit Full Sleeves Printed Casual Shirt",
    img: "https://rukminim1.flixcart.com/image/872/1046/ku8pbbk0/shirt/i/x/x/m-a1339-0001-levi-s-original-imag7ekfyfvgaeeb.jpeg?q=50",
    price: 1299,
    category: "Men",
    inStock: true,
    fastDelivery: true,
    rating: 5,
    originalPrice: 4000,
  },
  {
    _id: uuid(),
    title: "AWG Men's Cotton Regular Fit Solid Polo Neck T-Shirt",
    img: "https://m.media-amazon.com/images/I/61WTEg8WWbL._AC_UL480_FMwebp_QL65_.jpg",
    price: 1299,
    category: "Men",
    inStock: true,
    fastDelivery: true,
    rating: 3,
    originalPrice: 1600,
  },
  {
    _id: uuid(),
    title: "Men Regular Fit Checkered Cut Away Collar Casual Shirt",
    img: "https://rukminim1.flixcart.com/image/880/1056/xif0q/shirt/s/a/o/-original-imagaryeurszdgmr-bb.jpeg?q=50",
    price: 1299,
    category: "Men",
    inStock: true,
    fastDelivery: true,
    rating: 2,
    originalPrice: 2500,
  },
  {
    _id: uuid(),
    title: "Solid Men Polo Neck Black T-Shirt",
    img: "https://rukminim1.flixcart.com/image/872/1046/l1b1oy80/t-shirt/j/j/b/xl-rhp0931-red-tape-original-imagcwc3ppnxcspv.jpeg?q=50",
    price: 2299,
    category: "Men",
    inStock: true,
    fastDelivery: true,
    rating: 3,
    originalPrice: 2500,
  },
  {
    _id: uuid(),
    title: "Boys Printed Pure Cotton T Shirt  (Multicolor, Pack of 1)",
    img: "https://rukminim1.flixcart.com/image/872/1046/xif0q/kids-ethnic-set/j/j/n/3-4-years-whitejabla-ftc-fashions-original-imaft8pzfzegxtyb-bb.jpeg?q=50",
    price: 1499,
    category: "Kids",
    inStock: true,
    fastDelivery: true,
    rating: 4,
    originalPrice: 2000,
  },
  {
    _id: uuid(),
    title: "Casual Shirt, Waistcoat and Pant Set  (Brown Pack of 1)",
    img: "https://rukminim1.flixcart.com/image/872/1046/kdxfc7k0hlty2aw-0/kids-ethnic-set/g/i/0/7-8-years-1-skbc01-ftc-fashions-original-imafuschbzhwp3ng.jpeg?q=50",
    price: 1999,
    category: "Kids",
    inStock: true,
    fastDelivery: true,
    rating: 3,
    originalPrice: 3000,
  },
  {
    _id: uuid(),
    title: "Solid Men Round Neck Yellow T-Shirt",
    img: "https://rukminim1.flixcart.com/image/872/1046/kl8ccy80/t-shirt/s/g/s/4xl-mt21-p01-mustard-alan-jones-original-imagyeg8naqfu3xk.jpeg?q=50",
    price: 1099,
    category: "Men",
    inStock: true,
    fastDelivery: true,
    rating: 2,
    originalPrice: 1200,
  },

  {
    _id: uuid(),
    title: "Jockey Men's Gym Muscle Vest",
    img: "https://m.media-amazon.com/images/I/71X89dtTEzL._UX569_.jpg",
    price: 1299,
    category: "Men",
    inStock: true,
    fastDelivery: true,
    rating: 3,
    originalPrice: 1900,
  },
];
